fix non catastrophic exception
Failed to inflate ColorStateList, leaving it to the framework
java.lang.UnsupportedOperationException: Can't convert to color:

Signed-off-by: lsitec333.asato <andre.shoji@lsitec.org.br>